---
title: "baseball"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Readers already familiar with the sport of baseball may prefer to skip to "Project aim."

### What is baseball?

Baseball is a bat-and-ball sport whose modern form originated in the United States in the nineteenth century. It is closely related to bat-and-ball sports of European origin, such as cricket.

While baseball enjoys popularity in many nations (mostly in the Americas and Japan), the United States' Major League Baseball (MLB), founded in 1903, is recognized as the world's premier baseball league. MLB is composed of two "leagues", the National and American Leagues, each divided into three divisions; East, Central and West. There are 30 teams in the MLB, of which 29 are based in the United States and one in Canada. At the conclusion of each baseball season (played roughly from early April to late October), the champions of the National League and the American League compete against each other in a best-of-seven "World Series."

### Rules of baseball

The rules of baseball may be found at http://mlb.mlb.com/documents/0/8/0/268272080/2018_Official_Baseball_Rules.pdf. What follows is a brief summary of the aspects of the sport necessary to understand the project at hand. Note that for clarity, throughout this paper male pronouns are used when a singular pronoun is called for. (There has never been a female player in the MLB, the organization of interest in this study.)

A baseball game, under normal circumstances, consists of 9 "innings". For the first half of each inning, the away team plays offense and attempts to score while the home team plays defense and attempts to prevent scoring. These roles are reversed in the second half of each inning. The team with the most runs (points) at the end of nine innings wins the game. "Extra" innings are played if necessary to break ties.

Throughout the game, nine players of the offensive team take turns, one at a time, "at-bat." They stand opposite the opposing "pitcher" and eight other defensive players, carrying a bat. The pitcher throws the ball towards the batter, trying to get the batter "out." The batter, for his part, attempts to hit the ball with the bat and "reach base". As the inning continues, the offensive players who have reached base attempt to touch each of the four bases in order, wihtout getting out. If an offensive player successfully touches the fourth base, "home plate," his team is awarded one run.

When a pitch has been thrown, if the batter swings and misses, or fails to swing at a pitch that is deemed by the umpire to be within the "strike zone," this is a "strike." If there are three strikes against a batter, he is "out" and another teammate becomes the next batter. When a team has recorded three outs, the half-inning is over and the opposing team comes to bat.

A batter may avoid "striking out" either by walking (the batter is awarded first base if the pitcher throws four pitches outside of the strike zone without the batter swinging), or by making contact with the ball and putting it "in play." Even if a batter puts a ball in play, he may still get "out," mainly in the following ways: the batted ball is caught on the fly, the batter is tagged by a defensive player with the ball while not on a base, or a defensive player with the ball touches first base before the batter (now the "batter-runner") has touched first base. While the batter is not out, he is free to touch as many bases as he can in order; he generally elects to stop at the farthest base possible without getting out, at which point he is safe and cannot get out until he leaves the base on a subsequent play.

If a batter reaches base, he may stop at first base, second base, third base or home plate. Ignoring some technicalities, those results are designated as a single, double, triple, or home run, respectively. If a batter gets on base but does not reach home plate (i.e., he does not score), he may still be able to reach home plate when a new teammate at-bat puts the ball in play. Clearly, for a given at-bat, a home run is the best option, followed in order by triple, double, and single. 

The rules governing play beyond this are complex, but they are not crucial to understand the project at hand. 

### Baseball statistics and wOBA

Baseball statistics have been recorded and studied for well over one hundred years. Possibly due to the fact that individual actions are relatively easily separable in baseball (i.e., teammates have less of an effect on each other's individual outcomes than in other sports), baseball has also perhaps been the sport most responsible for the origination and explosion of advanced sports analytics, whereby analysts identify measured player accomplishments that are most likely to translate to runs and wins and apply sophisticated statistical methods to make predictions and inferences about such quantities. A pioneer of this work in the late 20th century was Bill James, honored as one of Time Magazine's 100 most influential people in the world for 2006. Advanced baseball statistics, often known as "sabermetrics," entered into popular culture with Michael Lewis's 2003 bestseller *Moneyball: The Art of Winning an Unfair Game* about the Oakland Athletics' adoption of sabermetric principles, later adapted into the Oscar-nominated 2011 film *Moneyball*.

In this project, we are going to focus on the [sabermetric statistic *wOBA*](https://library.fangraphs.com/offense/woba/), which stands for "weighted on-base percentage." For a given sequences of a batter's plate appearances, is calculated as follows:

\[
wOBA = \frac{0.7\cdot(W+HBP)+0.9\cdot S+1.25\cdot D+1.6 \cdot T+2 \cdot HR}{PA-SacB}
\]

where W is the number of walks, HBP is the number of times hit-by-pitch (same outcome as walk), S is the number of singles, D is the number of doubles, T is the number of triples, HR is the number of home runs, PA is the number of plate appearances, and SacB is the number of sacrifice bunts. The weights in the numerator are calculated so as to represent the number of additional runs scored that can be expected by a given batting outcome, relative to that batter instead getting out. The denominator normalizes the statistic to account for the fact that some batters have more opportunities to hit (plate appearances) than others. (Sacrifice bunts are a technicality that can be ignored for the purposes of understanding.)

Therefore, $wOBA$ may be seen as a kind of "gold-standard" batting statistic; a player's $wOBA$ represents a relative measure of how many runs he tends to contribute each time he goes to bat.

### Project aim

Although $wOBA$ is a very useful statistic because it attempts to tie batter outcomes directly to run production, it is still "outcome-oriented" in that it is purely a function of the batter's game-recorded outcomes. Outcome-oriented statistics are convenient and justifiable in the longterm, but they are not necessarily optimal for player evaluation and the prediction of future results.

As an analogy, imagine a novice poker player facing off against a professional. Since the game of poker has elements of both luck and skill, it is possible for the novice to beat the professional in a given match. An outcome-oriented analysis would conclude that the novice *played better* than the professional. But an informed observer would likely be able to recognize that the professional's decisions throughout the game were actually superior, and he just happened to be unlucky. In much the same way, a batter's recorded outcomes (single, double, etc.) are the result both of his own actions (hitting the ball and running), and factors outside of his control (defensive quality and stadium factors). 

In 2015, a new technology called [Statcast](https://en.wikipedia.org/wiki/Statcast) was introduced to Major League Baseball stadiums. The tool uses high-speed cameras to take measurements of ball and player movements during a game. Statcast produces a robust set of data about each baseball play and is a very exciting opportunity for baseball analytics.

Using Statcast data, we may be able to identify the value of *batter-based* actions, we might arrive at an expectation of *wOBA* that is a more accurate indicator of batter quality than *wOBA* itself, which only considers the outcomes of each play.

This concept is not new; the analytics firm at Statcast calculates a statistic called [*xwOBA*](http://m.mlb.com/glossary/statcast/expected-woba), short for "expected wOBA," which attempts to determine the *wOBA* that could be expected from the batter's contact with the ball, as measured by launch speed, or the velocity at which the ball leaves the bat, and launch angle, or the vertical angle at which the ball leaves the bat. However, to our knowledge the algorithm used to calculate the statistic is not publicly available. We will calculate our own version of expected wOBA which uses many more variables than what Statcast claims to. We believe that one of these variables, sprint speed, should add value to the model because it is a batter-level variable that is an important factor in whether a given batted ball is converted into a single, double, or triple. Another factor that we believe will be important is spray angle, which is an engineered feature that approximates the horizontal angle describing the direction in the field that the ball was hit. We also include other variables *outside* the batter's control and attempt to marginalize over their league-distribution. It is debatable whether such a procedure should produce better predictions of *wOBA* than simply omitting those variables from the beginning, but including them allows us to answer independent questions of interest with regard to what external factors affect batting outcomes.


### Data 

$554,149$ samples of baseball event data are collected from [Baseball Savant](https://baseballsavant.mlb.com/statcast_search). For this investigation, we are interested in event-related batted ball-outcomes; that is, those at-bats that end with either i) an out, ii) a single, iii) a double, iv) a triple, or v) a home run. $377,050$ ($68.6\%$) of the samples produced a batted ball event. Predictors of interest are broken into two categories: those that the batter has control of, and those the batter does not have control of. $100\%$ of the dataset contains valid outcome variables, whereas $4.6\%$ of the dataset contains incomplete predictor rows. The dataset consists of of $239,521$ ($66.5\%$) of outs, $75,935$ ($21.1\%$) of singles, $24,345$ ($6.7\%$) of doubles, $2356$ ($.6\%$) of triples, and $17,624$ ($4.9\%$) of home runs. The predictors of interest are organized as follows:

1. Batter-Controlled Predictors
    + Launch Speed: The velocity the ball is hit.
    + Launch Angle: The angle of the ball's trajectory, relative the ground.
    + Spray Angle: The angle of of the ball's trajectory, relative the field. This feature was approximated using a coordinate system of where the ball was fielded. This was accomplished using a formula from a contributor at [The Hardball Times](https://tht.fangraphs.com/research-notebook-new-format-for-statcast-data-export-at-baseball-savant/).
    + Strike Zone, Top: The top of the batter's strike zone.
    + Strike Zone, Bottom: The bottom of the batter's strike zone.
    + Ball/Strike Count: The current number of balls/strikes in the count.
    + Batting Handedness: The side of the plate from which the batter hits.
    + Sprint Speed: The top sprint speed of the batter measured from that season. This data was also acquired from [Baseball Savant](https://baseballsavant.mlb.com/sprint_speed_leaderboard) in a separate data set.
2. Non-Batter-Controlled Predictors
    + Release Position of Pitch (x/y/z): The position the ball is release from.
    + Velocity of Pitch (x/y/z/cumulative): The velocity of the pitch.
    + Zone: The categorical zone in which the ball crosses the plate.
    + Pitcher Throwing Handedness: The hand from which the pitcher throws.
    + Movement of Pitch (x, z): The relative drop of the pitch in the x and z dimensions.
    + Plate Location (x, z): The location at which the ball crosses the plate.
    + Runner Positions: Whether there are runners on $1^{st}$, $2^{nd}$, or $3^{rd}$ bases at the time of the at-bat.
    + Acceleration of Pitch (x/y/z): The acceleration of the pitch.
    + Effective Speed: The effective speed of the pitch, based on where the pitcher releases the ball.
    + Release Spin Rate: The spin rate of the pitch.
    + Release Extension: The extension point at which the pitch is released.
    + Pitch Number: Total number of pitches thrown in current plate appearance.
    + Pitch Name: The label of the pitch type (fastball, curveball, changeup, etc.).
    + Fielder Defensive Statistics: The defensive rating of each of the $9$ fielders. The statistic used for these variables is [Defensive Runs Saved (DRS)](https://library.fangraphs.com/defense/drs/) which measures how many runs above or below average a fielder contributes to their team. In this model, the DRS for the player at that position in that season was normalized to $1,000$ innings played. The DRS measurements were obtained from [fangraphs.com](https://www.fangraphs.com/leaders.aspx?pos=all&stats=fld&lg=all&qual=y&type=1&season=2019&month=0&season1=2019&ind=0&team=0&rost=0&age=0&filter=&players=0&startdate=&enddate=).
    + Score of Batter's Team: Score of the team the batter is on.
    + Score of Pitcher's Team: Score of the team the pitcher is on.
    + Infield Fielding Alignment: The label of the infield fielding strategy employed (standard, strategic, shift).
    + Outfield Fielding Alignment: The label of the outfield fielding strategy employed (standard, strategic, extra outfielder).
    + Inning Number: The number of the inning.
    + Inning Half: Whether it is the top or bottom of the inning.
    
In the data set, $360,967$ batted ball events contained complete data for all the predictors listed above. This subset of the data was used for model training.
  
    
## Exploratory analysis

### Launch Angle & Launch Speed

Since the advent of Statcast, launch angle and launch speed have widely been considered the best indicators of batted ball quality. Batted 

## Model

For this analysis, we chose to employ a Random Forest that inputs the predictors described above to predict one of the five batted ball outcomes. In the Random Forest model, we only considered batted balls that contained values for all the predictors above. 

One reason for choosing a Random Forest is that many of the predictors are highly interactive in their propensity to produce certain outcomes. Another reason is that the Random Forest allows us to include an extensive set of features, so that we can identify which features are most important in predicting outcomes of batted balls. We expect that the features that are direct measurements of a batted ball, such as launch speed, launch angle, and spray angle, will be the most predictive of its outcome. However, we are also interested in identifying if other factors, such as attributes of the pitch, defense, or stadium, are important in predicting outcomes. Additionally, by including an expansive set of features, we can assess how well the most modern, cutting-edge measurements of baseball plays can predict their outcomes.

### SPORF

The particular implementation of Random Forest employed is [SPORF](https://arxiv.org/abs/1506.03410), or Sparse Projection Oblique Randomer Forests. Traditional Random Forests build upon the axis-aligned decision tree: that is, the trees split only along features that exist within the feature space of the dataset of interest. By contrast, oblique decision trees extend the split criterion to along one or more features. For a simple example, consider for instance when the outcome of interest is whether or not it is raining today. If we know that it rained yesterday, and we know that it is forecast to rain tomorrow, either one of these pieces of information may individually provide valuable insights into predicting whether or not it is raining today. However, considered together; that is, that it rained yesterday and it is forecast to rain tomorrow, these two pieces of information may yield a much stronger prediction to whether it is raining today. While an axis-aligned decision tree may well be capable of generating trees that can recognize this particular pattern, as the feature space widens, the tree depth to identify these "oblique" tendencies in the feature space grow exponentially. Trees of substantial depth unfortunately tend to lose generalizability and have a tendency to overfit the sample data. Fortunately, numerous strategies (for example, [XGBoost](https://arxiv.org/abs/1603.02754)) have been introduced to generate "oblique" ensembles: random forests built upon decision trees wholse split criterions include linear combinations, rotations, and other transforms of the individual features. SPORF was developed to accomodate these oblique strategies, while providing many of the computational benefits of a traditional axis-aligned method (particularly, computational efficiency, insensitivity to a large proportion of noisy inputs, and interpretability). For these reasons, as well as the ease-of-use of `SPORF` in the `R` programming language and heavy `C` optimization, we choose to use `SPORF`s for our project.

### rfxwOBA

As stated above, we will use the results of the random forest model to produce our own expectation of *wOBA*. In order to produce this, we will use a permutation strategy to create a marginal distribution of expected *wOBA* for each batted ball event. The process will be executed as follows:

* Assign the appropriate wOBA weights to all non-batted ball events (0 for strikeouts and 0.7 for walks and hit by pitch)
* Subset the data to only include the batted ball events and randomly impute any missing predictors from the complete cases
* Randomly shuffle the rows for every predictor except for five predictors which are direct measurements of the batter *(batter handedness, launch speed, launch angle, spray angle and sprint speed)*
* Produce predicted probabilities of each outcome for each event by running this modified data set through the random forest
* Linearly combine these predicted probabilities with the corresponding *wOBA* weights to produce an expected *wOBA* value for each event

We chose to keep the five predictors listed above as constant in this process because we believe that those five variables are the best indicators of a batter's skill in producing a positive batted ball outcome.

We will repeat this procedure 1000 times to produce 1000 expected *wOBA* values for each event. We will consider this to be a sample from the distribution of expected *wOBA* values for an event given the five "batter" measurements held constant. Using these values for a given player over a season, we can produce 1000 expected *wOBA* values for that player in that season. We can visaulize and analyze the distribution of these expected *wOBA* values, as well as produce a point estimate of expected *wOBA* by taking the mean of the 1000 values. We will refer to this point estimate as *rfxwOBA* or "random forest expected wOBA".

We will produce these distributions and metrics in two ways. Once by obtaining estimates of the entire data set (2017-2019 seasons) on a model trained on the complete cases of the entire data set. We will also fit three additional random forest models, with each of them holding out one season's data from the training set. Then we will produce the estimates for the events in a given season using the model that did not include that season's data in the training set.

In order to assess the validity of this metric for projecting a player's future performance, we will calculate league-wide correlations of a season's *rfxwOBA* to the following season's *wOBA*, and comparing it to the correlation of the season's *wOBA* to the following season's *wOBA*. A stronger association between *rfxwOBA* and next season's *wOBA* than *wOBA* and next season's *wOBA* will suggest evidence that *rfxwOBA* is a better predictor of a player's future performance than actual *wOBA*. We will also assess the reliability of *rfxwOBA* by calculating the correlation of league-wide *rfxwOBA* in a season to itself in the following season.

The data exported from Baseball Savant also includes a column labeled `estimated_woba_using_speedangle` for each event. There is not documentation on how these values are calculated. We will also produce expected *wOBA* values from these values, referred to as "baseball savant expected wOBA" or *bsxwOBA*. We will also consider this metric in assessing player projection and metric reliability.

## Results

### Random Forest Prediction of Event Outcomes

Random Forests are trained using the $359,781$ samples of complete-predictor batted-ball event data. For model evaluation, we consider two cross-validative strategies. First, we perform traditional $50$-fold Cross Validation, in which we separate the samples randomly into $50$ folds, and for iterations $i=1, ..., 50$, train the model on all folds $j \neq i$, and use the $i^{th}$ fold as the testing set. The purpose of this approach is primarily for developing insights into how effectively, the model is making predictions, and in particular, where and when it is getting predictions wrong. We evaluate our strategy using a Confusion Matrix. A confusion matrix is constructed by generating a $K\times K$ matrix, where the row-wise entries are the predicted outcomes, and the column-wise entries are the true outcomes. A single $(i, j)$ entry represents the fraction times the true items of class $j$ are predicted to be part of the $i^{th}$ class. Ideally, an effective model will have true outcomes predominantly being predicted into the correct class, in which the on-diagonal entries will exceed the off-diagonal entries.

![Figure 1: The average confusion matrix after $50$-fold cross-validation. Individual cells are colored by the fraction of samples with the true outcome indicated by the column predicted into the predicted outcome indicated by the row (that is, each row sums to $100$), and the average percent is reported along with the standard deviation across all entries. As we can see based on the confusion matrix, the model performs exceptionally well for both Outs and Home runs, as these two classes individually see an accuracy rate of $93.8\%$ and $72.6\%$, with the accuracy for singles more modest at $52.9\%$. The model is relatively ineffective for predicting both doubles and triples, which are most commonly mislabelled as outs. Of note, Outs represent over $60\%$ of the dataset, so it is not surprising that most of the incorrect predictions are mislabelled as outs (as the leaf nodes will consist $>60\%$ of outs).](../rf/figs/xv_folds.png)

Second, we compare our model to the "random guess" classifier, which simply guesses the maximally proportionate class. An effective classifier will certainly outperform the "random guess" classifier, so this serves as an effective benchmark for a minimal acceptable classification accuracy. The average accuracy is $79.0\pm.4\%$, whereas the random guess classifier has only $66.6\pm .6\%$ accuracy, indicating that our SPORF classifier substantially outperforms the random guess classifier. 

### Random Forest Feature Importances

Second, we are concerned with discerning which features provide, or do not provide, meaningful insights into our predictive task. To this extent, we consider two popular metrics for evaluating the "importance" of features: the Gini importance (G, for Gini) and simply counting the number of times a feature is used across the forest (C, for count). Unlike the count strategy, the gini importance weights a feature's importance by how much it improves the purity a resulting split criterion divides the sample data at a particular node (that is, how much it improves the separation of classes within the dataset). For instance in a $2$ class problem, if a particular feature and threshold chosen at a particular node divides the data evenly into the two classes, this feature would receive a high importance, whereas a feature and threshold chosen at a particular node that does little to divide between the two classes would have a lower importance. Both strategies are popular for determining the importance of features leveraged in a Random Forest.

![Figure 2: Assessing the relative importance of features, as determined by the Gini Importance Metric or the Count Metric. Both metrics are normalized across features by the maximum for each respective metric, to make the scales comparable. The top ten features by importance are identical across both Gini and the Count metric. Of note, the Gini clearly places higher relative importance on the Launch Angle, which has the interpretation that the launch angle is extremely effective for creating splits that result in more pure sub-samples at nodes within the random forest.](../rf/figs/feat_imp.png)


### rfxwOBA

## Conclusion